// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Dc;

namespace WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.image", b =>
                {
                    b.Property<int>("imgID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("imgName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imgcaption")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("imgID");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("WebApi.Models.paymentDetails", b =>
                {
                    b.Property<int>("paymentDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cardNumber")
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("cardOwnnerName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("expirationDate")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("securityCode")
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("paymentDetailsID");

                    b.ToTable("paymentDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
